apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs
spec:
  replicas: 1
  selector:
    role: nfs
  template:
    metadata:
      labels:
        role: nfs
    spec:
      containers:
      - name: nfs
        image: xujintao/nfs:1.0-centos
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: hostpath-pvc
      nodeSelector:
        beta.kubernetes.io/nfs-ready: "true"
