language: go

go:
#- "1.9"
- "1.10.x"

services:
- docker

env:
- TESTGIN_VER=1.0

# 默认install是go get -t ./...
install:
#- go get -v -t ./...
- docker pull golang:1.10.3-alpine3.8
- docker run 
  --rm 
  -v $TRAVIS_BUILD_DIR:/go/src/github.com/xujintao/testgin 
  -w /go/src/github.com/xujintao/testgin 
  golang:1.10.3-alpine3.8 
  sh -c "go version && go build -v"
- export TESTGIN_BUILD_VER=${TESTGIN_VER}.${TRAVIS_BUILD_NUMBER}
- docker build -t xujintao/testgin:$TESTGIN_BUILD_VER ./

# 默认script是go test -v ./...
script:
# 看看镜像有没有打成功
- docker images

# 全链路测试需要的条件太苛刻，暂时放弃
# - go test -v ./...

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push xujintao/testgin:$TESTGIN_BUILD_VER