language: go

go:
#- "1.9"
- "1.10.x"

services:
- docker

env:
- TESTGIN_VER=1.0.0

# 默认install是go get -t ./...
install:
#- go get -v -t ./...
- docker pull xujintao/docker4go:1.10.3
- docker run -v $TRAVIS_BUILD_DIR:/go/src/github.com/xujintao/testgin xujintao/docker4go:1.10.3
- export TESTGIN_BUILD_VER=${TESTGIN_VER}.${TRAVIS_BUILD_NUMBER}
- docker build -t xujintao/testgin:$TESTGIN_BUILD_VER ./

# 默认script是go test -v ./...
script:
# 看看镜像有没有打成功
- docker images

# 全链路测试需要的条件太苛刻，暂时放弃
# - go test -v ./...

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push xujintao/testgin:$TESTGIN_BUILD_VER