apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: mysql-master
  nfs:
    # FIXME: use the right IP
    server: 10.254.0.7
    path: "/exports/mysql/master"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-slave-0
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: mysql-slave-0
  nfs:
    # FIXME: use the right IP
    server: 10.254.0.7
    path: "/exports/mysql/slave-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-slave-1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: mysql-slave-1
  nfs:
    # FIXME: use the right IP
    server: 10.254.0.7
    path: "/exports/mysql/slave-1"
