apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  serviceName: mysql-master
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
      - name: mysql-master
        image: paulliu/mysql-master:0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_REPLICATION_USER
          value: 'demo'
        - name: MYSQL_REPLICATION_PASSWORD
          value: 'demo'
        volumeMounts:
        - name: mysql-master-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
