apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  serviceName: mysql-slave
  replicas: 2
  selector:
    matchLabels:
      name: mysql-slave
  template:
    metadata:
      labels:
        name: mysql-slave
    spec:
      containers:
      - name: mysql-slave
        image: paulliu/mysql-slave:0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_REPLICATION_USER
          value: 'demo'
        - name: MYSQL_REPLICATION_PASSWORD
          value: 'demo'
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
